<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        Permission::insert([
            [
                'id' => 12,
                'name' => 'Settings',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 24,
                'activity_id' => null,
                'created_at' => '2026-07-29 20:15:32',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 13,
                'name' => 'Site Settings',
                'menu_type' => 'sub_menu',
                'menu_key' => 'site_settings',
                'order_no' => 26,
                'activity_id' => '1',
                'created_at' => '2026-07-29 20:16:34',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 17,
                'name' => 'Permissions',
                'menu_type' => 'sub_menu',
                'menu_key' => 'permissions',
                'order_no' => 20,
                'activity_id' => '1,2,3,4,5,6',
                'created_at' => '2026-07-29 22:02:41',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 19,
                'name' => 'Activities',
                'menu_type' => 'sub_menu',
                'menu_key' => 'activities',
                'order_no' => 16,
                'activity_id' => '1,2,3,4',
                'created_at' => '2026-08-15 22:27:19',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 20,
                'name' => 'Administrations',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 15,
                'activity_id' => null,
                'created_at' => '2026-08-15 22:30:35',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 21,
                'name' => 'Roles',
                'menu_type' => 'sub_menu',
                'menu_key' => 'roles',
                'order_no' => 17,
                'activity_id' => '1,2,3,4',
                'created_at' => '2026-08-15 22:32:42',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 22,
                'name' => 'Plot Types',
                'menu_type' => 'sub_menu',
                'menu_key' => 'plot_types',
                'order_no' => 25,
                'activity_id' => '1,2,3,4,8',
                'created_at' => '2026-08-17 19:00:57',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 23,
                'name' => 'People',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 1,
                'activity_id' => null,
                'created_at' => '2026-08-17 19:02:23',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 24,
                'name' => 'Plot And Units',
                'menu_type' => 'sub_menu',
                'menu_key' => 'plot_and_units',
                'order_no' => 2,
                'activity_id' => '1,2,3,4,5',
                'created_at' => '2026-08-17 19:03:04',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 25,
                'name' => 'Collection Management',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 7,
                'activity_id' => null,
                'created_at' => '2026-08-17 19:03:38',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 27,
                'name' => 'Collections',
                'menu_type' => 'sub_menu',
                'menu_key' => 'collections',
                'order_no' => 9,
                'activity_id' => '1,3,4,8,9',
                'created_at' => '2026-08-18 20:38:56',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 28,
                'name' => 'Users',
                'menu_type' => 'sub_menu',
                'menu_key' => 'users',
                'order_no' => 19,
                'activity_id' => '1,2,3,4',
                'created_at' => '2026-09-01 17:23:24',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 29,
                'name' => 'Roads',
                'menu_type' => 'sub_menu',
                'menu_key' => 'roads',
                'order_no' => 18,
                'activity_id' => '1,2,3,4',
                'created_at' => '2026-09-02 21:37:44',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 30,
                'name' => 'Collectors',
                'menu_type' => 'sub_menu',
                'menu_key' => 'collectors',
                'order_no' => 10,
                'activity_id' => '1,3,4,10',
                'created_at' => '2026-09-05 22:38:17',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 31,
                'name' => 'Upoad Members',
                'menu_type' => 'sub_menu',
                'menu_key' => 'upload_members',
                'order_no' => 3,
                'activity_id' => '1',
                'created_at' => '2026-09-15 20:49:18',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 32,
                'name' => 'Payment Management',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 4,
                'activity_id' => null,
                'created_at' => '2026-09-16 16:42:35',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 33,
                'name' => 'My Payments',
                'menu_type' => 'sub_menu',
                'menu_key' => 'my_payments',
                'order_no' => 5,
                'activity_id' => '1,9,11',
                'created_at' => '2026-09-16 16:46:21',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 36,
                'name' => 'Payments Report',
                'menu_type' => 'sub_menu',
                'menu_key' => 'payments_report',
                'order_no' => 6,
                'activity_id' => '1,9',
                'created_at' => '2026-09-16 17:01:27',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 37,
                'name' => 'Bill Generator',
                'menu_type' => 'sub_menu',
                'menu_key' => 'bill_generator',
                'order_no' => 8,
                'activity_id' => '1,2,12',
                'created_at' => '2026-09-28 08:13:06',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 38,
                'name' => 'SMS Managements',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 11,
                'activity_id' => null,
                'created_at' => '2026-09-28 08:14:27',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 39,
                'name' => 'Bulksms',
                'menu_type' => 'sub_menu',
                'menu_key' => 'bulk_sms',
                'order_no' => 12,
                'activity_id' => '1',
                'created_at' => '2026-09-28 08:22:19',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 40,
                'name' => 'Draft SMS',
                'menu_type' => 'sub_menu',
                'menu_key' => 'draft_sms',
                'order_no' => 13,
                'activity_id' => '1,2,3,4',
                'created_at' => '2026-09-28 08:23:03',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 41,
                'name' => 'SMS History',
                'menu_type' => 'sub_menu',
                'menu_key' => 'sms_history',
                'order_no' => 14,
                'activity_id' => '1,9',
                'created_at' => '2026-09-28 08:40:41',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 42,
                'name' => 'Access Control',
                'menu_type' => 'main_menu',
                'menu_key' => null,
                'order_no' => 21,
                'activity_id' => null,
                'created_at' => '2026-09-28 10:39:02',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 43,
                'name' => 'Role Wise Permission',
                'menu_type' => 'sub_menu',
                'menu_key' => 'role_permission',
                'order_no' => 22,
                'activity_id' => '1',
                'created_at' => '2026-09-28 10:39:36',
                'updated_at' => '2026-09-28 12:14:12',
            ],
            [
                'id' => 44,
                'name' => 'User Wise Permission',
                'menu_type' => 'sub_menu',
                'menu_key' => 'user_permission',
                'order_no' => 23,
                'activity_id' => '1',
                'created_at' => '2026-09-28 10:40:16',
                'updated_at' => '2026-09-28 12:14:12',
            ],
        ]);
    }
}